from . import views
from django.urls import path

app_name = 'Madlibs'
urlpatterns = [
    path('', views.index, name="index"),
    path('madlib/', views.madlib, name="madlib"),
    path('madlib_a/', views.madlib_a, name="madlib_a"),
    path('madlib_b/', views.madlib_b, name="madlib_b"),
    path('madlib_c/', views.madlib_c, name="madlib_c"),
    path('madlib_d/', views.madlib_d, name="madlib_d"),
    path('madlib_e/', views.madlib_e, name="madlib_e"),
    path('madlib_f/', views.madlib_f, name="madlib_f"),
    path('madlib_g/', views.madlib_g, name="madlib_g"),
    path('madlib_h/', views.madlib_h, name="madlib_h"),
    path('madlib_i/', views.madlib_i, name="madlib_i"),
    path('madlib_j/', views.madlib_j, name="madlib_j"),
    path('madlib_k/', views.madlib_k, name="madlib_k"),
    path('madlib_l/', views.madlib_l, name="madlib_l"),
    path('madlib_m/', views.madlib_m, name="madlib_m"),
    path('madlib_n/', views.madlib_n, name="madlib_n"),
    path('madlib_o/', views.madlib_o, name="madlib_o"),
    path('a/', views.a, name="a"),
    path('b/', views.b, name="b"),
    path('c/', views.c, name="c"),
    path('d/', views.d, name="d"),
    path('e/', views.e, name="e"),
    path('f/', views.f, name="f"),
    path('g/', views.g, name="g"),
    path('h/', views.h, name="h"),
    path('i/', views.i, name="i"),
    path('j/', views.j, name="j"),
    path('k/', views.k, name="k"),
    path('l/', views.l, name="l"),
    path('m/', views.m, name="m"),
    path('n/', views.n, name="n"),
    path('o/', views.o, name="o"),
]