# Generated by Django 4.0.3 on 2022-03-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madlib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('superlative_ending_est', models.CharField(max_length=200)),
                ('body_part', models.CharField(max_length=200)),
                ('verb_end_ing', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
                ('day_of_week', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('time_span', models.CharField(max_length=200)),
                ('adverb', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('celebrity', models.CharField(max_length=200)),
                ('verb_end_s', models.CharField(max_length=200)),
                ('silly_word', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('illness', models.CharField(max_length=200)),
                ('noun_plural', models.CharField(max_length=200)),
                ('relative', models.CharField(max_length=200)),
                ('verb_end_ed', models.CharField(max_length=200)),
                ('amount_of_time', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('noun_end_ers', models.CharField(max_length=200)),
                ('girl_name', models.CharField(max_length=200)),
                ('boy_name', models.CharField(max_length=200)),
                ('animal_plural', models.CharField(max_length=200)),
                ('kitchen_appliance', models.CharField(max_length=200)),
                ('food_plural', models.CharField(max_length=200)),
                ('liquid', models.CharField(max_length=200)),
                ('government_position', models.CharField(max_length=200)),
                ('holiday', models.CharField(max_length=200)),
                ('crime', models.CharField(max_length=200)),
                ('fruit', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('measurement', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=200)),
                ('weapon_plural', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
            ],
        ),
    ]
