# Generated by Django 4.0.3 on 2022-03-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Madlibs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madlib',
            name='adjective',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='adverb',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='amount_of_time',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='animal',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='animal_plural',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='body_part',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='boy_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='celebrity',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='company',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='crime',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='day_of_week',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='event',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='food_plural',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='fruit',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='game',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='girl_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='government_position',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='holiday',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='illness',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='kitchen_appliance',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='last_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='liquid',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='location',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='measurement',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='month',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='noun',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='noun_end_ers',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='noun_plural',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='number',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='occupation',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='person',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='place',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='relative',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='silly_word',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='superlative_ending_est',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='time_span',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='verb',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='verb_end_ed',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='verb_end_ing',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='verb_end_s',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='madlib',
            name='weapon_plural',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
