# Generated by Django 4.0.3 on 2022-03-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Madlibs', '0002_alter_madlib_adjective_alter_madlib_adverb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madlib',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
